### ISSUE TITLE
Problem handling skills with multiple words on the "/whobot who knows" command

### ISSUE THREAD

**Issue by RaneWallin** [belcurv/whobot#15]
Users can add skills with multiple words, but when you do "/whobot who knows multiple word skill" the list only shows the first word

Below result for "/whobot who knows donut eating"

![image](https://cloud.githubusercontent.com/assets/12719774/25051931/fa9da78a-2103-11e7-9ce3-74d006d84eab.png)

**Comment by belcurv** [comment]
Fixed with commit# 3ef5264
